[#macro notificationTitleText title]
-------------------------------------------------------------------------------
${title}
-------------------------------------------------------------------------------
[/#macro]

[#macro notificationTitleIm title]
${title}
-------------------------------------------------------------------------------
[/#macro]

[#macro buildNotificationTitleText build buildNumber]
    [#if build.parent?has_content]
    ${build.project.name} > [#if build.parent.master?has_content]${build.parent.master.buildName} > [/#if]${build.parent.buildName} > #${buildNumber} > ${build.buildName}[#t]
    [#else]
    ${build.project.name} > [#if build.master?has_content]${build.master.buildName} > [/#if]${build.buildName} > #${buildNumber}[#t]
    [/#if]
[/#macro]

[#macro showEmailFooter]
--
This message is automatically generated by Atlassian Bamboo (Start Build Notification Plugin)
[/#macro]

